modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="seethrough"
version="1.0"
displayName="See Through Invisibility"
authors="YourName"
description="Allows seeing invisible players"
